import Head from 'next/head'
import React from 'react'
import Header from '../Components/Header/Header'
import Ride from '../Components/Rides/Ride'
import axios from 'axios';

export default function Home({posts,city, state, user_info}) {
  return (
    <React.Fragment>
      <Head>
        <title>Edvore App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet' />
      </Head>
      <Header user_info={user_info}/>
      <Ride rides_arr={posts} city_list={city} state_list={state} />
    </React.Fragment>
  )
}

const getShortestDistance = (station_code, station_code_arr) => {
  var shortest_distance = Math.abs(station_code - station_code_arr[0])
  for (let i of station_code_arr) {
    if (Math.abs(station_code-i) < shortest_distance) {
      shortest_distance = Math.abs(station_code-i)
    }
  }
  return shortest_distance
}
const getCityState = (posts) => {
  let city = new Set()
  let state = new Set()
  for(let i of posts) {
    city.add(i.city)
    state.add(i.state)
  }
  return {
    city_arr: [...city],
    state_arr: [...state]
  }
}

export async function getStaticProps() {
  const res = await axios.get('https://assessment.api.vweb.app/rides')
  let posts = await res.data

  //calling user api
  const user_api_res = await axios.get('https://assessment.api.vweb.app/user')
  let user_info = await user_api_res.data
  let city, state = null
  if (posts.length > 0) {
    for (let i in posts) {
      const station_code_arr = posts[i].station_path
      const distance = getShortestDistance(user_info.station_code, station_code_arr)
      posts[i].distance = distance
    }
    let {city_arr, state_arr} = getCityState(posts)
    city = Array.from(city_arr)
    state = Array.from(state_arr)
  }
  
  return {
    props: {
      posts,
      city,
      state,
      user_info
    },
  }
}